basic:
  fit_n_jobs: 4
  inference_n_jobs: 4
  memory_limit_gb: 32
  time_limit_sec: 3600

lgb_base_params:
  learning_rate: 0.05
  num_leaves: 32
  num_threads: 4

xgb_linear_base_params:
  eta: 0.1

