[tool.poetry]
name = "LightAutoML"
version = "0.1.0"
description = "Библиотека автоматического построения моделей"
authors = ["Рыжков Александр <AMRyzhkov@sberbank.ru>",
           "Вахрушев Антон <AGVakhrushev@sberbank.ru>",
           "Дамдинов Ринчин <RGDamdinov@sberbank.ru>"]
readme = "README.md"
homepage = "https://github.com/sberbank-ai-lab/LightAutoML"
repository = "https://github.com/sberbank-ai-lab/LightAutoML"
classifiers = [
    "Programming Language :: Python :: 3.7",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Natural Language :: Russian",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.6.1"
numpy = "*"
scipy = "*"
pandas = "*"
scikit-learn = "*"
lightgbm = "2.*"
optuna = "*"
torch = "*"
holidays = "*"
networkx = "*"
cmaes = "*"
log-calls = "*"
pyyaml = "*"
sphinx = "*"
sphinx-rtd-theme = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"